name: ronda_vigilante
description: "Um aplicativo de ronda para vigilantes."

publish_to: "none"

version: 1.0.0+1

environment:
  # Agora podemos usar uma versão mais recente do SDK
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  shared_preferences: ^2.2.3
  geolocator: ^12.0.0
  connectivity_plus: ^6.0.3
  sqflite: ^2.3.3+1
  intl: ^0.19.0
  path: ^1.9.1
  # O pacote 'path' é omitido para evitar conflitos com o flutter_test.

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
