name: ronda_vigilante
description: "Um aplicativo de ronda para vigilantes."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  workmanager: ^0.8.0
  connectivity_plus: ^6.0.3
  sqflite: ^2.3.3+1
  intl: ^0.19.0
  path: ^1.9.1
  permission_handler: ^11.0.0 # ✅ Adicionado para tratar permissões em tempo de execução

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
